[package]
name = "emb-23-debug-basics-251130"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt = "0.7.5"
embedded-hal = "1.0.0"
microbit-v2 = "0.16.0"
panic-halt = "1.0.0"
rtt-target = "0.6.2"

cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
